#!/usr/bin/env python

import argparse
import re
from Bio import SeqIO


parser = argparse.ArgumentParser(description = "Parse the CDS start/end locations from a file containing all transcripts in a dataset. It will look in HisatIndex for a file named e.g. S12_all_transcripts.fa, generated by gffread using -W and -C flags, and write out a file containing the name of that transcript and its start and end locations (1-indexed).")
parser.add_argument("dataset", help = "The name of the dataset e.g. S12")
args = parser.parse_args()

pattern = re.compile("CDS=(\d*)-(\d*)")

outfh = open("%s_transcript_CDS_start_end_locations.txt" % args.dataset, "w")
# write header line
outfh.write("Transcript" + "\t" + "Start (1-based)" + "\t" + "End" + "\n")

infh = open("./HisatIndex/%s_all_transcripts.fa" % args.dataset, "r")

for record in SeqIO.parse(infh, "fasta"):  
    m = pattern.search(record.description)
    outstr = "\t".join([record.id, m.group(1), m.group(2)]) + "\n"
    outfh.write(outstr)

